version: '3.8'

services:
  node:
    image: ${COMPOSE_PROJECT_NAME}/node:16-alpine
    build: images/node
    command: /bin/sh -c "npm run start:debug"
    restart: on-failure
    ports:
      - '${HTTP_PORT}:80'
    volumes:
      - ../:/var/www
  minio:
    image: minio/minio:RELEASE.2022-11-10T18-20-21Z.fips
    command: server --console-address :9001 /data
    restart: on-failure
    ports:
      - '${S3_PORT}:9000'
      - '${S3_CONSOLE_PORT}:9001'
    volumes:
      - s3:/data
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
  storage:
    image: ducthach1401/storage-service:0.0.1
    restart: on-failure
    env_file:
      - ../.env.storage
  picfit:
    image: thoas/picfit:0.9.0
    restart: on-failure
    ports:
      - '${PICFIT_PORT}:3001'
    volumes:
      - ./images/picfit/config.json:/var/config.json
    environment:
      - PICFIT_CONFIG_PATH=/var/config.json
  postgres:
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./images/postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
volumes:
  s3:
  postgres:
